# Generated by Django 3.2 on 2021-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
