# Generated by Django 3.2 on 2021-04-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_item_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='has_sizes',
        ),
    ]
